Change all scripts to fish

diff --git a/bin/executable_search b/bin/executable_search
--- a/bin/executable_search
+++ b/bin/executable_search
@@ -1,38 +1,93 @@
-#!/bin/bash
+#!/usr/bin/env fish
 
-if [ "$XDG_SESSION_TYPE" != 'wayland' ]; then
-  read -r site search <<< "$(rofi -theme-str 'window {height: 23%;}' -markup -mesg "Default: Search google&#x0a;!gh: Search github&#x0a;!rd: Search rdocumentation&#x0a;!r: Search reddit&#x0a;!yt: Search youtube&#x0a;!t: Search twitch&#x0a;!sp: Search spotify&#x0a;!ddg: Search duckduckgo&#x0a;!w: Search wikipedia" -dmenu -p "Search:" | cut -d " " -f 1,2-)"
-fi
+# Define search menu entries
+set menu_text "Default: google
+!gh: github
+!rd: rdocumentation
+!r: reddit
+!yt: youtube
+!t: twitch
+!sp: spotify
+!ddg: duckduckgo
+!w: wikipedia"
 
-if [ "$XDG_SESSION_TYPE" == 'wayland' ]; then
-  read -r site search <<< "$(fuzzel --dmenu --prompt "search:" | cut -d " " -f 1,2-)"
-fi
+# URL encode function
+function url_encode
+    string replace -a ' ' '+' -- $argv | string replace -a '&' '%26' | string replace -a '?' '%3F' | string replace -a '=' '%3D' | string replace -a '#' '%23'
+end
 
-if [ -n "$search" ]
-then
-        case "$site" in
-                ("") exit 1 ;;
-                ("!"[Gg][Hh]) xdg-open https://github.com/search?q="$search" ;;
-                ("!"[Rr][Dd]) xdg-open https://www.rdocumentation.org/search?q="$search" ;;
-                ("!"[Rr]) xdg-open https://reddit.com/search?q="$search"&sort=relevance&t=all ;;
-                ("!"[Yy][Tt]) xdg-open https://www.youtube.com/results?search_query="$search" ;;
-                ("!"[Tt]) xdg-open https://twitch.tv/search?term="$search" ;;
-                ("!"[Ss][Pp]) xdg-open https://open.spotify.com/search/"$search" ;;
-                ("!"[Dd][Dd][Gg]) xdg-open https://duckduckgo.com/?q="$search" ;;
-                ("!"[Ww]) xdg-open https://www.wikipedia.org/wiki/"$search" ;;
-                (*) xdg-open https://www.google.com/search?q="$site $search" ;;
-        esac
-else                
-        case "$site" in
-                ("") exit 1 ;;
-                ("!"[Gg][Hh]) xdg-open https://github.com ;;
-                ("!"[Rr][Dd]) xdg-open https://www.rdocumentation.org ;;
-                ("!"[Rr]) xdg-open https://reddit.com ;;
-                ("!"[Yy][Tt]) xdg-open https://www.youtube.com ;;
-                ("!"[Tt]) xdg-open https://twitch.tv ;;
-                ("!"[Ss][Pp]) xdg-open https://open.spotify.com ;;
-                ("!"[Ww]) xdg-open https://www.wikipedia.org ;;
-                ("!"[Dd][Dd][Gg]) xdg-open https://duckduckgo.com ;;
-                (*) xdg-open https://www.google.com/search?q="$site $search" ;;
-        esac
-fi
+# Choose menu program based on session type
+if test "$XDG_SESSION_TYPE" != 'wayland'
+    if command -v rofi >/dev/null
+        set selection (echo $menu_text | rofi -dmenu -p "search:" -mesg "search options")
+    else
+        echo "Error: rofi not found" >&2
+        exit 1
+    end
+else
+    if command -v fuzzel >/dev/null
+        set selection (echo $menu_text | fuzzel --dmenu --prompt-only "search:")
+    else
+        echo "Error: fuzzel not found" >&2
+        exit 1
+    end
+end
+
+# Exit if no selection
+if test -z "$selection"
+    exit 0
+end
+
+# Check if the selection starts with a bang command
+set first_word (string split ' ' $selection)[1]
+
+if string match -q '!*' $first_word
+    # This is a bang command
+    set bang_cmd (string sub -s 2 $first_word)  # Remove the ! prefix
+    set parts (string split ' ' $selection --max 2)
+    
+    # Set up search URL based on the bang command
+    switch $bang_cmd
+        case "gh"
+            set search_url "https://github.com/search?q="
+            set home_url "https://github.com"
+        case "rd"
+            set search_url "https://www.rdocumentation.org/search?q="
+            set home_url "https://www.rdocumentation.org"
+        case "r"
+            set search_url "https://reddit.com/search?q="
+            set home_url "https://reddit.com"
+        case "yt"
+            set search_url "https://www.youtube.com/results?search_query="
+            set home_url "https://www.youtube.com"
+        case "t"
+            set search_url "https://twitch.tv/search?term="
+            set home_url "https://twitch.tv"
+        case "sp"
+            set search_url "https://open.spotify.com/search/"
+            set home_url "https://open.spotify.com"
+        case "ddg"
+            set search_url "https://duckduckgo.com/?q="
+            set home_url "https://duckduckgo.com"
+        case "w"
+            set search_url "https://www.wikipedia.org/wiki/"
+            set home_url "https://www.wikipedia.org"
+        case "*"
+            set search_url "https://www.google.com/search?q="
+            set home_url "https://www.google.com"
+    end
+    
+    if test (count $parts) -eq 1
+        # Just the bang command, open the homepage
+        xdg-open $home_url
+    else
+        # Search term provided
+        set search $parts[2]
+        set encoded_search (url_encode $search)
+        xdg-open $search_url$encoded_search
+    end
+else
+    # No bang command, search Google for the entire input
+    set encoded_search (url_encode $selection)
+    xdg-open "https://www.google.com/search?q=$encoded_search"
+end
